### PR TITLE
Lce leak fix

### PR DESCRIPTION
**Pull request by leonardo2204**

### CODE REVIEW

**Comment by leonardo2204** [comment]
Just updated the gradle but it's not building, any ideas why ?

**Comment by sockeqwe** [comment]
You also have to set the version in `.travis` file

**Comment by leonardo2204** [comment]
Hey man, sorry for the several builds, I'm new to Travis... 
I can't figure out what's going on, could you help me on this ?

**Comment by sockeqwe** [comment]
Sorry, i'm not on the pc right now. But I will take this over. No worries,
I will merge your pull request tomorrow and fix travis afterwards

Leonardo Ferrari <notifications@github.com> schrieb am Mo., 24. Okt. 2016,
21:22:

**Comment by leonardo2204** [comment]
Thank you man so much !
I'd really appreciate if you could drop me a message here explaining what I did wrong on Travis, to learn from it !
Thanks

**Pull request merged**
