### PR TITLE
#290: Added null checks to prevent NPEs with ViewGroupDelegate cleanup

### PR DESCRIPTION
**Pull request by laalto**
and fixed some typos

### CODE REVIEW

**Comment by sockeqwe** [comment]
This looks good. Im just wondering if there is a better way to deal with that... Let me think about it this evening...
Thanks!

**Comment by laalto** [comment]
Any news with this? Would want to get rid of the crashes but would not want to deploy a forked version of Mosby.

**Comment by sockeqwe** [comment]
Sorry, i was too busy lately and have forgotten about this. I have
dedicated some time this weekend. This should be fixed by Monday.
I appologize for any inconveniences this may have caused.

Lauri Aalto <notifications@github.com> schrieb am Mi., 17. Jan. 2018, 09:39:

**Comment by sockeqwe** [comment]
Hm, I tired to reproduce the actual issue to ensure this fixes the described issue.

So basically you start an activity and in `Activity.onCreate()` you call `Activity.finish()`. In the layout of the Activity there is some custom ViewGroup that is powered by Mosby such as a `MvpFrameLayout`, right?

**Comment by laalto** [comment]
In the real application almost like that: Code in `Activity#onResume()` checks for session validity and calls `Activity#finishAffinity()` to throw the user back to login screen in case the session is no longer valid. And yes, there's a bottom navigation bar in the top-level activity that is powered by `MvpFrameLayout`.

I have actually been doing some testing with this by deploying this fix in our internal QA builds and monitoring how it's doing. Before doing that there used to be a background radiation of 1..3 crashes a day from our internal QA, without QA people being able to come up with repro steps, only suspicions that "something times out in the background". There have been no more crashes after deploying this change.

**Comment by sockeqwe** [comment]
Ah I see, let me try to reproduce this with  `Activity#onResume()` and `Activity#finishAffinity()`

**Comment by sockeqwe** [comment]
Thanks!

**Pull request merged**
