### PR TITLE
LceAnimator magic values cleanup

### PR DESCRIPTION
**Pull request by sswierczek**
Hi!
I cleaned magic values in LceAnimator. Not sure if you want dimen.xml in mvp module but for me it looks much better now.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks, will take a look tomorrow

**Comment by sockeqwe** [comment]
Looks good to me, thanks!
I would appreciate if you could put the "hard coded" resources  `android.R.integer.config_longAnimTime` also into a `int.xml` file, so that other could override this if needed.

Otherwise I will do that after merging your pull request.

**Comment by sswierczek** [comment]
Sure it will be even better. I changed that.

**Comment by sockeqwe** [comment]
Thanks, I really should have implemented like that from the very beginning!


Sebastian Świerczek <notifications@github.com> schrieb am Do., 25. Feb.
2016, 22:50:

**Pull request merged**
