### PR TITLE
creating an MvpRxPresenter generic class

### PR DESCRIPTION
**Pull request by fahimk**
This is what I came up with, let me know what you think. I ran the MvpLceRxPresenter tests and they pass.

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks, I will have a look later this week!

**Comment by sockeqwe** [comment]
Do you think it's necessary to rename the methods to `onRxError()` , `onRxNext()` and `onRxComplete`? It breaks backward compatibilty. At least I have over 70 presenters in my apps, where I would have to rename the methods

**Comment by fahimk** [comment]
Sorry, didn't realize that. I can rename the private methods, then keep the abstract ones the same.

**Comment by fahimk** [comment]
I've updated the change list to use the same method names.

**Comment by sockeqwe** [comment]
Thanks!

**Pull request merged**
