### PR TITLE
Sce viewstate

### PR DESCRIPTION
**Pull request by leonardo2204**
First (Again) commit on the SCE (Send-Content-Error) part of Mosby.
Not sure if it's the best implementation of all use-cases, really appreciate feedbacks and suggestion (help also ;)) to implement this cool feature !

### CODE REVIEW

**Comment by sockeqwe** [comment]
I think adding this is not important anymore, is it?

**Comment by leonardo2204** [comment]
@sockeqwe You mean the feature or the code itself, since it's ouf of date ?

**Comment by sockeqwe** [comment]
Sorry, I mean't the feature

**Comment by leonardo2204** [comment]
@sockeqwe No problem :)
Is there any other new way of doing this ? Sorry for the dumb question, I'm kinda out of date with Android for a while haha

**Comment by sockeqwe** [comment]
Not really in MVP / ViewState but with new MVI module this whole ViewState stuff is not needed anymore ...

**Comment by leonardo2204** [comment]
Cool, thanks for the feedback, gonna dive in a little further on this pattern !

**Pull request closed without merging**
