### PR TITLE
Add public access modifier in interface.

### PR DESCRIPTION
**Pull request by leesunghyun**
I think that there is no need public access modifier in the interface.
What do you think?

### CODE REVIEW

**Comment by sockeqwe** [comment]
Thanks for your pull request!

Removing the public modifier makes no difference. All interface methods are public anyway. So it's basically just a matter of style. However, if we will ever see java 9 on android than it makes a difference if interfaces methods are defined as public or "default" package visibility (or private) since java 9 allows visibility modifiers on interfaces. Therefore I prefer to keep the `public` modifiers on interfaces (if we ever would see java 9 we have to explicitly add them again) 

As already said, nowadays in java 7 it's just a (personal) matter of style. Therefore I have to thank you for your work, but I don't see much benefit in removing the public modifier.

What do you think?

**Comment by leesunghyun** [comment]
I think that is to reconsider the modifier of all of the interface when you migrate to the java 9.
It's matter of style as you said, it is right.
I think have to unify style in a project.
would you like add public modifier to ActivityMvpDelegate, ActivityMvpDelegateCallback?

**Comment by sockeqwe** [comment]
Yes, my coding style (since I'm also programming java 8 on server side) is that I always use `public` modifiers and I thought I have applied that coding style to mosby as well, but it seems that I have not applied that on all interfaces like `ActivityMvpDelegate` etc.
I think it would be a good idea to add the modifiers to that one rather than removing modifiers from others.

**Comment by leesunghyun** [comment]
Yeah, I respect you.
I unify coding style for interface.
Add the modifiers in interface.
I want to contribute in your project.

**Comment by sockeqwe** [comment]
Thanks for that!
You are welcome to contribute in **OUR** project!

**Pull request merged**
